apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pod-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-csi
  csi:
    driver: local.csi.driver
# Optional settings:
# directory: name of the directory to create/mount (defaults to volumeHandle if not set)
# dirmode: Directory Access Modes, defaults to 0755 if not set. Can also be changed after the PV/directory has been created.
    volumeAttributes:
      directory: "test-pod"
      dirmode: "0700"
# This csi driver uses the volumeHandle as the directory name to create/mount
# if no directory has been set in the volumeAttributes
    volumeHandle: test-pod-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pod-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: test-pod-pv
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-csi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh", "-c", "date >> /data/test.txt && cat /data/test.txt && echo done"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: test-pod-pvc
